using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestConsoleApp
{
    public class EmployeeTable
    {
        public int EmployeeId { get; set; }
        public bool IsActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public decimal Salary { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public DateTime BirthDate { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        public static List<EmployeeTable> GetEmployees()
        {
            return new List<EmployeeTable>()
{
    new EmployeeTable {
        EmployeeId = 1,
        IsActive = true,
        FirstName = "John",
        LastName = "Smith",
        Title = "CEO",
        Department = "Executive",
        Salary = 200000,
        Email = "john.smith@testcompany.ai",
        Address = "123 Main St",
        City = "Jacksonville",
        State = "FL",
        Zip = "32258",
        Country = "USA",
        BirthDate = new DateTime(1975, 1, 1),
        StartDate = new DateTime(2021, 10, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 2,
        IsActive = true,
        FirstName = "Jane",
        LastName = "Doe",
        Title = "CTO",
        Department = "Executive",
        Salary = 180000,
        Email = "jane.doe@testcompany.ai",
        Address = "456 Elm St",
        City = "Miami",
        State = "FL",
        Zip = "33101",
        Country = "USA",
        BirthDate = new DateTime(1980, 2, 2),
        StartDate = new DateTime(2021, 10, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 3,
        IsActive = true,
        FirstName = "Michael",
        LastName = "Johnson",
        Title = "CFO",
        Department = "Finance",
        Salary = 170000,
        Email = "michael.johnson@testcompany.ai",
        Address = "789 Oak St",
        City = "Orlando",
        State = "FL",
        Zip = "32801",
        Country = "USA",
        BirthDate = new DateTime(1978, 3, 3),
        StartDate = new DateTime(2021, 11, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 4,
        IsActive = true,
        FirstName = "Emily",
        LastName = "Williams",
        Title = "COO",
        Department = "Operations",
        Salary = 160000,
        Email = "emily.williams@testcompany.ai",
        Address = "101 Pine St",
        City = "Tampa",
        State = "FL",
        Zip = "33601",
        Country = "USA",
        BirthDate = new DateTime(1982, 4, 4),
        StartDate = new DateTime(2021, 11, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 5,
        IsActive = true,
        FirstName = "David",
        LastName = "Brown",
        Title = "VP of Sales",
        Department = "Sales",
        Salary = 150000,
        Email = "david.brown@testcompany.ai",
        Address = "102 Maple St",
        City = "Tallahassee",
        State = "FL",
        Zip = "32301",
        Country = "USA",
        BirthDate = new DateTime(1985, 5, 5),
        StartDate = new DateTime(2021, 12, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 6,
        IsActive = true,
        FirstName = "Susan",
        LastName = "Taylor",
        Title = "VP of Marketing",
        Department = "Marketing",
        Salary = 145000,
        Email = "susan.taylor@testcompany.ai",
        Address = "103 Birch St",
        City = "Gainesville",
        State = "FL",
        Zip = "32601",
        Country = "USA",
        BirthDate = new DateTime(1983, 6, 6),
        StartDate = new DateTime(2021, 12, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 7,
        IsActive = true,
        FirstName = "Robert",
        LastName = "Anderson",
        Title = "VP of HR",
        Department = "HR",
        Salary = 140000,
        Email = "robert.anderson@testcompany.ai",
        Address = "104 Cedar St",
        City = "Sarasota",
        State = "FL",
        Zip = "34230",
        Country = "USA",
        BirthDate = new DateTime(1986, 7, 7),
        StartDate = new DateTime(2021, 12, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 8,
        IsActive = true,
        FirstName = "Linda",
        LastName = "Clark",
        Title = "Director of IT",
        Department = "IT",
        Salary = 135000,
        Email = "linda.clark@testcompany.ai",
        Address = "105 Walnut St",
        City = "Naples",
        State = "FL",
        Zip = "34101",
        Country = "USA",
        BirthDate = new DateTime(1981, 8, 8),
        StartDate = new DateTime(2022, 1, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 9,
        IsActive = true,
        FirstName = "James",
        LastName = "Martinez",
        Title = "Director of Engineering",
        Department = "Engineering",
        Salary = 130000,
        Email = "james.martinez@testcompany.ai",
        Address = "106 Chestnut St",
        City = "St. Petersburg",
        State = "FL",
        Zip = "33701",
        Country = "USA",
        BirthDate = new DateTime(1984, 9, 9),
        StartDate = new DateTime(2022, 1, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 10,
        IsActive = true,
        FirstName = "Patricia",
        LastName = "Lewis",
        Title = "Director of Product",
        Department = "Product",
        Salary = 125000,
        Email = "patricia.lewis@testcompany.ai",
        Address = "107 Hickory St",
        City = "Fort Myers",
        State = "FL",
        Zip = "33901",
        Country = "USA",
        BirthDate = new DateTime(1987, 10, 10),
        StartDate = new DateTime(2022, 1, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 11,
        IsActive = true,
        FirstName = "Thomas",
        LastName = "Hall",
        Title = "Director of Customer Support",
        Department = "Customer Support",
        Salary = 120000,
        Email = "thomas.hall@testcompany.ai",
        Address = "108 Spruce St",
        City = "Boca Raton",
        State = "FL",
        Zip = "33401",
        Country = "USA",
        BirthDate = new DateTime(1988, 11, 11),
        StartDate = new DateTime(2022, 2, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 12,
        IsActive = true,
        FirstName = "Barbara",
        LastName = "Walker",
        Title = "Senior Software Engineer",
        Department = "Engineering",
        Salary = 115000,
        Email = "barbara.walker@testcompany.ai",
        Address = "109 Redwood St",
        City = "Palm Beach",
        State = "FL",
        Zip = "33480",
        Country = "USA",
        BirthDate = new DateTime(1989, 12, 12),
        StartDate = new DateTime(2022, 2, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 13,
        IsActive = true,
        FirstName = "Daniel",
        LastName = "King",
        Title = "Senior Product Manager",
        Department = "Product",
        Salary = 110000,
        Email = "daniel.king@testcompany.ai",
        Address = "110 Fir St",
        City = "Delray Beach",
        State = "FL",
        Zip = "33444",
        Country = "USA",
        BirthDate = new DateTime(1990, 1, 13),
        StartDate = new DateTime(2022, 3, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 14,
        IsActive = true,
        FirstName = "Elizabeth",
        LastName = "Harris",
        Title = "Software Engineer",
        Department = "Engineering",
        Salary = 105000,
        Email = "elizabeth.harris@testcompany.ai",
        Address = "111 Willow St",
        City = "Clearwater",
        State = "FL",
        Zip = "33755",
        Country = "USA",
        BirthDate = new DateTime(1991, 2, 14),
        StartDate = new DateTime(2022, 3, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 15,
        IsActive = true,
        FirstName = "Christopher",
        LastName = "Young",
        Title = "Product Manager",
        Department = "Product",
        Salary = 100000,
        Email = "christopher.young@testcompany.ai",
        Address = "112 Aspen St",
        City = "Hollywood",
        State = "FL",
        Zip = "33019",
        Country = "USA",
        BirthDate = new DateTime(1992, 3, 15),
        StartDate = new DateTime(2022, 4, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 16,
        IsActive = true,
        FirstName = "Jessica",
        LastName = "Nelson",
        Title = "Marketing Manager",
        Department = "Marketing",
        Salary = 95000,
        Email = "jessica.nelson@testcompany.ai",
        Address = "113 Cypress St",
        City = "Cape Coral",
        State = "FL",
        Zip = "33904",
        Country = "USA",
        BirthDate = new DateTime(1993, 4, 16),
        StartDate = new DateTime(2022, 4, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 17,
        IsActive = true,
        FirstName = "Matthew",
        LastName = "Wright",
        Title = "Sales Manager",
        Department = "Sales",
        Salary = 90000,
        Email = "matthew.wright@testcompany.ai",
        Address = "114 Sequoia St",
        City = "Coral Springs",
        State = "FL",
        Zip = "33065",
        Country = "USA",
        BirthDate = new DateTime(1994, 5, 17),
        StartDate = new DateTime(2022, 5, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 18,
        IsActive = true,
        FirstName = "Karen",
        LastName = "Perez",
        Title = "HR Manager",
        Department = "HR",
        Salary = 85000,
        Email = "karen.perez@testcompany.ai",
        Address = "115 Dogwood St",
        City = "Pembroke Pines",
        State = "FL",
        Zip = "33028",
        Country = "USA",
        BirthDate = new DateTime(1995, 6, 18),
        StartDate = new DateTime(2022, 5, 1),
        EndDate = null
    },
    new EmployeeTable {
        EmployeeId = 19,
        IsActive = false,
        FirstName = "Brian",
        LastName = "Lee",
        Title = "IT Support Specialist",
        Department = "IT",
        Salary = 80000,
        Email = "brian.lee@testcompany.ai",
        Address = "116 Magnolia St",
        City = "Ocala",
        State = "FL",
        Zip = "34470",
        Country = "USA",
        BirthDate = new DateTime(1996, 7, 19),
        StartDate = new DateTime(2022, 6, 1),
        EndDate = new DateTime(2024, 1, 1)
    },
    new EmployeeTable {
        EmployeeId = 20,
        IsActive = false,
        FirstName = "Amanda",
        LastName = "Rodriguez",
        Title = "Customer Support Specialist",
        Department = "Customer Support",
        Salary = 75000,
        Email = "amanda.rodriguez@testcompany.ai",
        Address = "117 Elm St",
        City = "Fort Lauderdale",
        State = "FL",
        Zip = "33301",
        Country = "USA",
        BirthDate = new DateTime(1997, 8, 20),
        StartDate = new DateTime(2022, 6, 1),
        EndDate = new DateTime(2024, 1, 2)
    }
};
        }
    }
}